export const CREATE_TEAM_ERROR = 'CREATE_TEAM_ERROR';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';

export const DELETE_TEAM_ERROR = 'DELETE_TEAM_ERROR';
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS';

export const UPDATE_TEAM_ERROR = 'UPDATE_TEAM_ERROR';
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS';

export const CLEAR_TEAM_STATE = 'CLEAR_TEAM_STATE';